name: firstCondaProject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
    - requests